### ISSUE TITLE
AttributeError: 'SlurmOpsManager' object has no attribute 'prepare_system_for_slurm'

### ISSUE THREAD

**Issue by devksingh4** [omnivector-solutions/charm-slurmctld#10]
Deploying via Juju 2.8.1 on MaaS 2.7.6 to Ubuntu 20.04

Following error when attempting to install from classic snap: 

```
unit-slurmctld-2: 02:19:13 ERROR unit.slurmctld/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 86, in <module>
    main(SlurmctldCharm)
  File "/var/lib/juju/agents/unit-slurmctld-2/charm/venv/ops/main.py", line 342, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-slurmctld-2/charm/venv/ops/framework.py", line 634, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-slurmctld-2/charm/venv/ops/framework.py", line 667, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 59, in _on_install
    self.slurm_ops_manager.prepare_system_for_slurm()
AttributeError: 'SlurmOpsManager' object has no attribute 'prepare_system_for_slurm'
unit-slurmctld-2: 02:19:13 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
unit-slurmctld-2: 02:19:34 ERROR unit.slurmctld/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 86, in <module>
    main(SlurmctldCharm)
  File "/var/lib/juju/agents/unit-slurmctld-2/charm/venv/ops/main.py", line 342, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-slurmctld-2/charm/venv/ops/framework.py", line 634, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-slurmctld-2/charm/venv/ops/framework.py", line 667, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 59, in _on_install
    self.slurm_ops_manager.prepare_system_for_slurm()
AttributeError: 'SlurmOpsManager' object has no attribute 'prepare_system_for_slurm'
```

**Comment by devksingh4** [comment]
I assume because it needs to be imported from the install.py of the SlurmOpsManager and not just from slurm_ops_manager?
